#!/bin/bash

# Launch the passed in URL as a web app in the default browser (or chromium if the default doesn't support --app).

browser=$(xdg-settings get default-web-browser)

case $browser in
google-chrome* | brave-browser* | microsoft-edge* | opera* | vivaldi* | helium*) ;;
*) browser="org.chromium.Chromium.desktop" ;;
esac

echo $browser
ls -alh /var/lib/flatpak/exports/share/applications/$browser
exec setsid uwsm-app -- $(sed -n 's/^Exec=//p' {~/.local,~/.nix-profile,/usr,/var/lib/flatpak/exports}/share/applications/$browser 2>/dev/null | head -1 | sed 's/ %[a-zA-Z]//g; s/@@u//g; s/@@//g') --app="$1" "${@:2}"
